name: Generate Documentation
on:
  release:
    types:
      - prereleased
      - released
jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build New Documentation
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: dokkaHtmlMultiModule
          properties: |
            release=true
      - name: Push New Documentation
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          branch: main
          message: 'doc: Added Latest Documentation ✨'
